myDjango/app/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from . import views

app_name = 'app'

urlpatterns = [
    path('add/', views.add, name='add')
    # path('',views.wel_ind),
    # path('list/',views.list),
    # path('toAdd/',views.toAdd),
    # path('add/',views.add),
    # path('toEdit/',views.toEdit),
    # path('edit/',views.edit),
 ]

myDjango/myDjango/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include
from app import views
from django.conf import settings


# def wel_ind(req):
#     return render(req, 'templates/wel_ind.html')

urlpatterns = [
    # path('welcome/', views.welcome),
    # path('wel_ind/',wel_ind),
    path('admin/', admin.site.urls),
    # path('index/',views.index),
    # path('save_data/',views.save_data),
    # path('db_handle/',views.db_handle),
    #
    # path('app/',include('app.urls')),
    # path('wel_ind/',wel_ind),
    # path('templates/',include('app.urls'))
    # url(r'^app/',include('app.urls')),
    #IMG file trans
    path('app/', include('app.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myDjango/app/models.py
from django.db import models

# Create your models here.
class UserInfo(models.Model):
    username = models.CharField(max_length=32)
    password = models.CharField(max_length=32)
    age = models.IntegerField()

class Test(models.Model):
     name = models.CharField(max_length=20)


class Artical(models.Model):
    title = models.CharField(max_length=100,verbose_name='文章标题')
    content = models.TextField(verbose_name='文章内容')
    author = models.CharField(max_length=30,verbose_name='作者')
    time = models.DateTimeField(auto_now=True, verbose_name='时间')

    class Meta:
        verbose_name_plural = '文章'
        verbose_name: '文章'

class Comment(models.Model):
    articalid = models.IntegerField(verbose_name='文章id')
    user = models.CharField(max_length=30, verbose_name='ls评论人')
    content = models.CharField(max_length=100,verbose_name='评论内容')
    time = models.DateTimeField(auto_now=True, verbose_name='时间')

class Person(models.Model):
    name = models.CharField(max_length=30)
    age = models.IntegerField()

    def __unicode__(self):
        return self.name

class IMG(models.Model):
    img = models.ImageField(upload_to='img')
    name = models.CharField(max_length=20)
    def __str__(self):
        return self.name

#create databases
class User(models.Model):
    name = models.CharField(max_length=50)
    heading = models.FileField(upload_to="img/")

    def __str__(self):
        return self.name

myDjango/app/forms.py
from django import forms


class AddForm(forms.Form):
    name = forms.CharField()
    heading = forms.FileField()

myDjango/app/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.shortcuts import HttpResponse
from django.views.decorators import csrf
# from app.models import Test
from app import models
from .forms import AddForm

list = [{"name":'good','password':'python'},{'name':'learning','password':'django'}]

def welcome(request):

    return HttpResponse("hello Django!")

def index(request):

    name = request.POST.get('name',None)
    password = request.POST.get('password',None)
    data = {'name':name, 'password':password}
    list.append(data)

    return render(request,'/index.html',{'form':list})

def save_data(request):
    data={}
    if request.POST:
        if 'add' in request.POST:
            test1 = models.Test(name=request.POST['add_data'])
            test1.save()
            data['result']='数据添加成功'
        if 'update' in request.POST:
            ID  = int(request.POST['update_data'])
            test1 = models.Test.objects.get(id=ID)
            test1.name='change'
            test1.save()
            data['result']='数据修改成功'
        if 'delete' in request.POST:
            ID = int(request.POST['delete_data'])
            test1=models.Test.objects.get(id=ID)
            test1.delete()
            data['result']='删除数据成功'
        if 'selete' in request.POST:
            ID = int(request.POST['select_data'])
            test1=models.Test.objects.get(id=ID)
            data['result']=test1.name

    return render(request, '/save_data.html',data)

def db_handle(request):
    """add number"""
    # models.UserInfo.objects.create(username='andy',password='123456', age=33)
    # dic = {"username":"christ","password":"123456","age":33}
    # models.UserInfo.objects.create(**dic)
    """#delete datanumber;"""
    # models.UserInfo.objects.filter(id=2).delete()
    """"update database;"""
    # models.UserInfo.objects.filter(id=1).update(age=18)

    # return HttpResponse('OK')

    """use html deal with databases:use file select data"""
    if request.method == "POST":
        models.UserInfo.objects.create(username=request.POST['username'],password=request.POST['password'],age=request.POST['age'])

    user_list_obj = models.UserInfo.objects.all()

    # return  render(request,'databases_deal.html',{'li':user_list_obj})
    return render(request, 'templates/static_css.html', {'li': user_list_obj})

def wel_ind(req):

    return render(req, 'templates/wel_ind.html')

def list(req):#表格信息
    data = {}
    list = models.Artical.objects.all()
    data['list'] = list
    return render(req, 'templates/app/list.html', data)

def toAdd(req):
    return render(req,'app/add.html')

def add(req):
    title = req.POST.get('title')
    content = req.POST.get('content')
    author = req.POST.get('author')
    article = models.Artical(title=title,content=content,author=author)
    article.save()
    return redirect('../list')

def toEdit(req):
    id = req.GET.get("id")
    article = models.Artical.objects.get(id=id)
    data = {}
    data['data'] = article

    return  render(req,'app/edit.html', data)

def edit(req):
    id = req.POST.get("id")
    title = req.POST.get('title')
    content = req.POST.get('content')
    author = req.POST.get('author')

    res = models.Artical.objects.filter(id=id).update(title=title,content=content,author=author)

    print("更新结果：{0}".format(res))

    return redirect('../list')

def hello(request):
    models.IMG.objects.filter(name='bg')
    img = models.IMG.objects.all()
    return render(request,'templates/welcome.html',{'img':img})

def add(request):
    if request.method == "POST":
        af = AddForm(request.POST, request.FILES)
        if af.is_valid():
            name = af.cleaned_data['name']
            heading = af.cleaned_data['heading']
            user = models.User(name=name, heading=heading)
            user.save()
            return render(request, 'templates/users/index.html', context={"user": user})
        else:
            af = AddForm()
            return render(request, 'templates/users/add.html', context={"af": af})

myDjango/templates/app/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>博客列表</title>
    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<form class="form-horizontal" role="form" method="post" action="../add/">
	<div class="form-group">
		<label class="col-sm-2 control-label">标题</label>
		<div class="col-sm-10">
			<input name="title" class="form-control-static" placeholder="输入标题">
		</div>
	</div>
    <div class="form-group">
		<label class="col-sm-2 control-label">内容</label>
		<div class="col-sm-10">
			<input name="content" class="form-control-static" placeholder="输入内容"/>
		</div>
	</div>
    <div class="form-group">
		<label class="col-sm-2 control-label">作者</label>
		<div class="col-sm-10">
			<input name="author" class="form-control-static" value="泡泡" placeholder="输入作者">
		</div>
	</div>
    <input type="submit" class="text-right btn btn-primary"/>
</form>
</body>
</html>

myDjango/templates/app/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>test</title>
</head>
<body>
    <table border="'1">
        <form action="/index" method="post">
            {% csrf_token %}
            <p>
                <label>用户名:</label>
                <input type="text" name='name'/>
            </p>
            <p>
                <label>密码:</label>
                <input type="text" name='password'/>
            </p>
            <p><input type="submit" value="提交"/></p>
        </form>
        <thead>
        <tr>
            <td>用户名</td>
            <td>密码</td>
        </tr>
        </thead>
        {%for  line in form%}
            <tr>
                <td>{{line.name}}</td>
                <td>{{line.password}}</td>
            </tr>
        {% endfor %}
    </table>
</body>
</html>

myDjango/templates/app/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>博客编辑</title>
    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<form class="form-horizontal" role="form" method="post" action="../edit/">
    <input type="hidden" name="id" value="{{ data.id }}"/>
	<div class="form-group">
		<label class="col-sm-2 control-label">标题</label>
		<div class="col-sm-10">
			<input name="title" class="form-control-static" value="{{ data.title }}" placeholder="输入标题">
		</div>
	</div>
    <div class="form-group">
		<label class="col-sm-2 control-label">内容</label>
		<div class="col-sm-10">
			<input name="content" class="form-control-static" value="{{ data.content }}" placeholder="输入内容"/>
		</div>
	</div>
    <div class="form-group">
		<label class="col-sm-2 control-label">作者</label>
		<div class="col-sm-10">
			<input name="author" class="form-control-static" value="{{ data.author }}" placeholder="输入作者">
		</div>
	</div>
    <input type="submit" class="text-right btn btn-primary"/>
</form>
</body>
</html>

myDjango/templates/app/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>博客列表</title>
    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <ul class="breadcrumb">
        <li><a href="/">Home</a></li>
        <li><a href="#">2018</a></li>
        <li class="active">十一月</li>
    </ul>
    <a href="../toAdd"><span type="button" class="btn btn-primary">添加文章</span></a>
    <table class="table">
	<caption>文章列表</caption>
   <thead>
      <tr>
         <th>ID</th>
         <th>标题</th>
         <th>内容</th>
         <th>作者</th>
         <th>时间</th>
         <th>操作</th>
      </tr>
   </thead>
   <tbody>
      {% for d in list %}
      <tr>
         <td>{{ d.id }}</td>
         <td>{{ d.title }}</td>
         <td>
             {% if d.content|length > 30 %}
                {{ d.content|slice:'30' }}...
                 {% else %}
                 {{ d.content }}
             {% endif %}
         </td>
         <td>{{ d.author }}</td>
         <td>{{ d.time }}</td>
         <td><a href="../toEdit/?id={{ d.id }}"><button type="button" class="btn btn-primary btn-xs">编辑</button></a></td>
      </tr>
      {% endfor %}
   </tbody>
</table>
</body>
</html>

myDjango/templates/databases_deal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django操作数据库</title>
</head>
<body>
    <table border="1">
        <tr>
            <th>用户名</th>
            <th>密码</th>
            <th>年龄</th>
        </tr>
        {% for item in li %}
        <tr>
            <td>{{ item.username }}</td>
            <td>{{ item.password }}</td>
            <td>{{ item.age }}</td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>

myDjango/templates/forward.html
<!DOCTYPE html>

<>

myDjango/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>test</title>
</head>
<body>
    <table border="'1">
        <form action="/index" method="post">
            {% csrf_token %}
            <p>
                <label>用户名:</label>
                <input type="text" name='name'/>
            </p>
            <p>
                <label>密码:</label>
                <input type="text" name='password'/>
            </p>
            <p><input type="submit" value="提交"/></p>
        </form>
        <thead>
        <tr>
            <td>用户名</td>
            <td>密码</td>
        </tr>
        </thead>
        {%for  line in form%}
            <tr>
                <td>{{line.name}}</td>
                <td>{{line.password}}</td>
            </tr>
        {% endfor %}
    </table>
</body>
</html>

myDjango/templates/save_data.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>数据库操作</title>
</head>
<body>
<form action="/save_data/" method="post">
    {% csrf_token %}
    <ul>
        <li>
            请输入名字<input type="text" name="add_data">
            <button type="submit" name="add">添加数据</button>
        </li>
        <li>
            请输入 ID<input type="text" name="update_data">
            <button type="submit" name="update">更新数据</button>
        </li>
        <li>
            请输入 ID<input type="text" name="delete_data">
            <button type="submit" name="delete">删除数据</button>
        </li>
        <li>
            请输入 ID<input type="text" name="select_data">
            <button type="submit" name="selete">查询数据</button>
        </li>
    </ul>

</form>
    <p>{{ result }}</p>
</body>
</html>

myDjango/templates/static_css.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django表单</title>
    <link type="text/css" href="/static/base.css" rel="external nofollow" rel="stylesheet"/>
</head>
<body>
    <table border="1">
        <tr>
            <th>用户名</th>
            <th>密码</th>
            <th>年龄</th>
        </tr>
        {% for item in li %}
        <tr>
            <td>{{ item.username }}</td>
            <td>{{ item.password }}</td>
            <td>{{ item.age }}</td>
        </tr>
        {% endfor %}
    </table>
    <form action="/db_handle/" method="post">
        <p>用户名：<input name="username"/></p>
        <p>密码：<input name="password"/></p>
        <p>年龄：<input name="age"/></p>
        <p><input type="submit" value="submit"/></p>
    </form>
</body>
</html>

myDjango/templates/users/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add</title>
</head>
<body>
  <h1>Add!</h1>
  <form method="post" enctype="multipart/form-data" action="{% url 'app:add' %}">
      {% csrf_token %}
      {{ af.as_p }}
      <input type="submit" value="OK"/>
  </form>
</body>
</html>

myDjango/templates/users/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details</title>
</head>
<body>
<p>{{user.name}}</p>
<img width="50%" height="50%" src="/media/{{ user.heading }}">
</body>
</html>

myDjango/templates/web_1_database.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <table border="'1">
        <thead>
        <tr>
            <td>用户名</td>
            <td>密码</td>
        </tr>
        </thead>
        {%for  line in form%}
            <tr>
                <td>{{line.name}}</td>
                <td>{{line.password}}</td>
            </tr>
        {% endfor %}
    </table>
</body>
</html>

myDjango/templates/wel_ind.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django admin</title>
</head>
<body>
  <h1>欢迎 hello python </h1>
  <ul>
    <li><a href="{% url 'admin' %}">后台管理</a></li>
    <li><a href="templates/app/">博客增删改查</a></li>
  </ul>
</body>
</html>

myDjango/templates/welcome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome</title>
</head>
<body>
  {% for i in img %}
  <img src="{{MEDIA_URL}}{{i.img}}">
  {% endfor %}
</body>
</html>